<?php 
$link = $_SERVER['REQUEST_URI'];
if($link =='/resume/')
{?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<title>Title</title>
<style>
    .page{
        background-color: #2C5364;
    }
    h1{
        font-size: 80px;
        font-weight: 0;
        text-align: center;
        margin-top: 70px;
    }
    h4{
        font-size: 60px;
        position: relative;
        top: -10px;
        text-align: center;
        margin-top: 10px;
    }
    p{
        margin-top: 30px;
        text-transform: capitalize;
        text-align: center;
    }
    .btn{
        margin:auto;
    }
    .mt-7{
        margin-top: 120px;
    }
    span{
        margin-bottom: 30px;
    }
    
        
    hr.new4 {
            margin-top: 30px;
            border: 3px solid white;
            border-radius: 5px;
            width: 55%;
        }
        
        .b1 {
            position: absolute;
            bottom: 10px;
            left: 140px;
        }
        
        .w-40 {
            width: 40%;
        }
        
        .p-10px {
            padding: 3px;
        }
</style>
</head>
<body>
<div class="container-fluid">
<div class="row p-4" style="background-color: #2C5364;">
    <div class="col-md-6">
        <span class="text-white p-3 rounded my-2" style="background-color: #00000073;">BUILD YOUR RESUME</span>
    </div>
    <div class="col-md-6 text-right">
        <a href="sign_up.php" class="btn btn-warning">Sign-up</a>
        <a href="sign_in.php" class="btn btn-warning"> Sign in</a>
    </div>
</div>
</div>
<div>
<b><h1 class="m-6">IMPRESSIVE RESUME</h1></b>
<h4>EASY ONLINE BUILDER</h4>
<p>Professional out-of-the-box resumes,instantly generated by the most advanced resume builder technology available<br><br>
<em>land your dream job with the perfect resume employers are looking for</em></p>
</div>
<div class="btn d-block bg-success w-50 mx-auto text-white mt-7"><h3>BUILD MY RESUME</h3></div>
    <div class="page mt-5">
    <h2 class="demo text-white m-md-2 p-3 text-center">PROFESSIONAL BUILD TEMPLATE</h2>
    <div class="content text-white mt-4 text-center w-100">Choose from 20+ tailored-built templates that have landed thousands of people like you<br> the jobs they were dreaming of.</div>
    <hr class="w-50 bg-white rounded mt-md-5">
    <div class="container  w-100 mb-3">
        <div class="row ">
            <div class="col-md-4 mt-4 mb-md-2 p-relative"><img src="../resume/images/main1.jpg" alt="" width="100%">
                <a href="sign_in.php"><button class="b1 w-40 p-10px bg-warning border rounded">Select</button></a>
            </div>
            <div class="col-md-4 mt-4 mb-md-2 p-relative"><img src="../resume/images/main2.jpg " alt=" " width="100% ">
                <a href="sign_in.php"><button class="b1 w-40 p-10px bg-warning border rounded">Select</button></a>
            </div>
            <div class="col-md-4 mt-4 mb-md-2 p-relative"><img src="../resume/images/main3.jpg " alt=" " width="100% ">
                <a href="sign_in.php"><button class="b1 w-40 p-10px bg-warning border rounded">Select</button></a>

            </div>
        </div>
    </div>
</div>
</body>
</html>
<?php
}elseif($link == "/resume/*"){
   echo "hi";
}
?>