<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<title>Title</title>
<style>
    .page{
        background-color: #2C5364;
    }
    h1{
        font-size: 80px;
        font-weight: 0;
        text-align: center;
        margin-top: 70px;
    }
    h4{
        font-size: 60px;
        position: relative;
        top: -10px;
        text-align: center;
        margin-top: 10px;
    }
    p{
        margin-top: 30px;
        text-transform: capitalize;
        text-align: center;
    }
    .btn{
        margin:auto;
    }
    .mt-7{
        margin-top: 120px;
    }
    span{
        margin-bottom: 30px;
    }
    
        
    hr.new4 {
            margin-top: 30px;
            border: 3px solid white;
            border-radius: 5px;
            width: 55%;
        }
        
        .b1 {
            position: absolute;
            bottom: 10px;
            left: 140px;
        }
        
        .w-40 {
            width: 40%;
        }
        
        .p-10px {
            padding: 3px;
        }
</style>
</head>
<body>
<<<<<<< HEAD
<div class="container-fluid">
<div class="row p-4" style="background-color: #2C5364;">
    <div class="col-md-6">
        <span class="text-white p-3 rounded my-2" style="background-color: #00000073;">BUILD YOUR RESUME</span>
    </div>
    <div class="col-md-6 text-right">
        <a href="#" class="btn btn-warning">Sign-up</a>
        <a href="#" class="btn btn-warning"> Sign in</a>
    </div>
</div>
</div>
<div>
<b><h1 class="m-6">IMPRESSIVE RESUME</h1></b>
<h4>EASY ONLINE BUILDER</h4>
<p>Professional out-of-the-box resumes,instantly generated by the most advanced resume builder technology available<br><br>
<em>land your dream job with the perfect resume employers are looking for</em></p>
</div>
<div class="btn d-block bg-success w-50 mx-auto text-white mt-7"><h3>BUILD MY RESUME</h3></div>
    <div class="page mt-5">
    <h2 class="demo text-white m-md-2 p-3 text-center">PROFESSIONAL BUILD TEMPLATE</h2>
    <div class="content text-white mt-4 text-center w-100">Choose from 20+ tailored-built templates that have landed thousands of people like you<br> the jobs they were dreaming of.</div>
    <hr class="w-50 bg-white rounded mt-md-5">
    <div class="container  w-100 mb-3">
        <div class="row ">
            <div class="col-md-4 mt-4 mb-md-2 p-relative"><img src="../resume/images/main1.jpg" alt="" width="100%">
                <a href=""><button class="b1 w-40 p-10px bg-warning border rounded">Select</button></a>
            </div>
            <div class="col-md-4 mt-4 mb-md-2 p-relative"><img src="../resume/images/main2.jpg " alt=" " width="100% ">
                <a href=""><button class="b1 w-40 p-10px bg-warning border rounded">Select</button></a>
            </div>
            <div class="col-md-4 mt-4 mb-md-2 p-relative"><img src="../resume/images/main3.jpg " alt=" " width="100% ">
                <a href=""><button class="b1 w-40 p-10px bg-warning border rounded">Select</button></a>
=======
  <?php
  include('../dashboard/includes/sidebar.php');
  ?>
  <div class="container-fluid">
    <h3>COMPLETE YOUR PERSONAL INFO</h3>
    <p class="text-muted">Employers will use this information to contact you.</p>
    <form class="col-md-8" method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>">
      <!-- <?php echo $_SERVER['PHP_SELF']; ?> -->
      <div class="row">
        <div class="form-group col">
          <label for="firstname">First Name</label>
          <input type="text" class="form-control" id="firstname" name="firstname" required>
        </div>
        <div class="form-group col">
          <label for="lastname">Last Name</label>
          <input type="text" class="form-control" id="lastname" name="lastname" required>
        </div>
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        <input type="text" name="address" id="address" class="form-control" size="50" required>
      </div>
      <div class="row">
        <div class="form-group col-6">
          <label for="city">City</label>
          <input type="text" name="city" id="city" class="form-control" size="20" required>
        </div>
        <div class="form-group col-3">
          <label for="country">Country</label>
          <input type="text" name="country" id="country" class="form-control" size="20" required>
        </div>
        <div class="form-group col-3">
          <label for="zip_code">zip Code</label>
          <input type="text" name="zip_code" id="zip_code" class="form-control" size="6" required>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-6">
          <label for="e_mail">E-mail address</label>
          <input type="email" name="e_mail" id="e_mail" class="form-control" size="50" required>
        </div>
        <div class="form-group col-6">
          <label for="mobile_number">Phone no</label>
          <input type="text" name="mobile_number" id="mobile_number" class="form-control" size="10" required>
        </div>
      </div>
      <button type="submit" class="btn btn-primary" name="submit">Submit</button>
    </form>
  </div>
  <?php
  include('../dashboard/includes/endsidebar.php');
  ?>
</body>
>>>>>>> b09484c89a7c2360ad3e2250d770c3f51df06d2e

            </div>
        </div>
    </div>
</div>
</body>
</html>